articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'  # 이름 지정하기
urlpatterns = [
    path('create/', views.create, name='create' ),
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    # user_pk == 게시글 작성자의 유저 아이디
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
    
]

review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),  
    path('accounts/', include('accounts.urls')),  # include의 의미가 accounts 앱에 있는 urls.py의 urlpatterns를 찾으라는 뜻이므로 accounts urls.py에 해당 변수가 있어야 한다.
    path('admin/', admin.site.urls),
]

articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=20) # max_length는 필수 속성
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True) # 데이터가 새로 추가되었을 때만.
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # n:n 관계를 좋아요 기능으로 구현한다. article과 user의 관계
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_articles')
    # user model을 불러올때는 꼭! settings.AUTH_USER_MODEL로 접근한다. (중요!)
    # article.liked_users.all()
    # user.liked_articles.all()
    class Meta:
        ordering = ('-pk', )


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='comments')
    class Meta:
        ordering = ('-pk',)
    def __str__(self):
        return self.content

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ['title', 'content',]

 
class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
       

articles/views.py
from django.views.decorators.http import require_POST, require_GET
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model  # follow 기능에 person의 user model을 찾기 위해
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ArticleForm, CommentForm
from .models import Article, Comment
from django.http import HttpResponse
from IPython import embed

# Create your views here.

@require_GET
def index(request):
    articles = Article.objects.all()
    return render(request, 'articles/index.html', {'articles': articles})


@require_GET
def detail(request, article_pk):
    # 사용자가 적어보낸 article_pk를 통해 detail page를 보여준다.
    # 특정 한개의 article을 꺼내는 방법
    article = get_object_or_404(Article, pk=article_pk)
    comments = article.comments.all()
    form = CommentForm()
    context = {
        'article' : article,
        'form' : form,
        'comments' : comments,  
        }
    return render(request, 'articles/detail.html', context)


@login_required
def create(request):
    if request.method == 'POST':
        # Article 생성 요청
        form = ArticleForm(request.POST)  # title, content
        
        if form.is_valid():
            article = form.save(commit=False)  # 저장하겠다라는 코드
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:  # GET 요청
        # Article 을 생성하기 위한 페이지를 달라는 요청

        form = ArticleForm()
    context = {'form' : form}
    
    return render(request, 'articles/create.html', context)


@login_required
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)

    if article.user == request.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, instance=article)  # 기존에 존재하는 인스턴스 안에 새롭게 받은 데이터로 바꾸겠다.
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article_pk)
            
        else: # GET으로 들어옴
            form = ArticleForm(instance=article)  # 특정 인스턴스를 form안에 넣은채로 form을 생성하겠다.
    else:
        return redirect('articles:detail', article_pk)
    context = {'form':form}
    return render(request,'articles/update.html',context )


# @login_required  # 쓰지 않는 이유 : 어차피 next_page의 url을 받아오는 method가 GET이므로 require_POST 에서 막힌다. 그러므로 다른 로직을 사용한다.(1
@require_POST
def delete(request, article_pk):
    if request.user.is_authenticated:
        # article_pk에 맞는 article을 꺼낸다.
        article = get_object_or_404(Article, pk=article_pk)
        # 삭제한다.
        if article.user == request.user:
            article.delete()
        else:
            return redirect('articles:detail', article_pk)
    return redirect('articles:index')
    
@login_required
def like(request, article_pk):
    # 유저와 아티클의 정보를 각 각 갖고 있어야 한다.
    user = request.user
    article = get_object_or_404(Article, pk=article_pk)
    if article.liked_users.filter(pk=user.pk).exists():
        user.liked_articles.remove(article)
    else:
        user.liked_articles.add(article)  # 유저가 좋아요 누른 아티클들에 현재 article을 추가하겠다.
    return redirect('articles:detail', article_pk)



@require_POST
def comments_create(request, article_pk):
    if request.user.is_authenticated:

        form = CommentForm(request.POST)
        article = get_object_or_404(Article, pk=article_pk)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.article = article
            new_form.user = request.user
            new_form.save()
        return redirect('articles:detail', article_pk)
    return HttpResponse('You are Unauthorized : 401 ERROR', status=401)


@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:

        comment = get_object_or_404(Comment, pk=comment_pk)
        
        if request.user == comment.user:
            comment.delete()
        else:
            return redirect('articles:index')

    return redirect('articles:detail', article_pk)


# 로그인한 유저가 게시글 유저를 follow 혹은 unfollow 기능을 구현한다.
@login_required
def follow(request, article_pk, user_pk):
    user = request.user  # 현재 로그인 되어있는 유저

    # get_user_model()을 불러오기 위해 임포트 한다.
    person = get_object_or_404(get_user_model(), pk=user_pk) # 게시글 작성자 유저
    
    if user in person.followers.all():  # 만약 게시글 작성자의 팔로워 중 로그인한 유저가 있다면, 언팔하겠다.
        person.followers.remove(user)
    else:
        person.followers.add(user)

    return redirect('articles:detail', article_pk)

articles/templates/articles/_follow.html
<div class="jumbotron text-center text-white bg-dark">
  <p class="lead mb-1">작성자 정보</p>
  <h1 class="display-4">{{ article.user.username }}</h1>
  <hr>
  <p class="lead">
  팔로잉 : {{ article.user.followings.all | length }} / 
  팔로워 : {{ article.user.followers.all | length }}
  </p>
  {% if user != article.user %}
  {% comment %} 만약 내가 게시글 작성자의 팔로워라면 언팔버튼 보여라 {% endcomment %}
  {% if user in article.user.followers.all %}
    <a href="{% url 'articles:follow' article.pk article.user.pk %}" class="btn btn-primary btn-lg">
      Unfollow
    </a>
  {% else %}
    <a href="{% url 'articles:follow' article.pk article.user.pk %}" class="btn btn-primary btn-lg">
      follow
    </a>
  {% endif %}
  {% endif %}
</div>

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block title %} Article::Create
{% endblock title %}

{% block container %}

{% comment %}  form이 필요함 왜? 입력할 창이 필요하니까 {% endcomment %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <button type="submit">생성하기</button>
</form>
{% endblock container %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}Article::Detail{% endblock title %}

{% block container %}


<h2>{{ article.title }}</h2>
{% if user.is_authenticated %}
<a href="{% url 'articles:like' article.pk %}">
{% if user in article.liked_users.all %}
<i class="fas fa-heart fa-3x" style='color : red'></i>
{% else %}
<i class="far fa-heart fa-3x" style='color : grey'></i>
{% endif %}
</a>
{% endif %}
<span>{{ article.liked_users.all | length }} 명이 이 글을 좋아합니다.</span>

<p>{{ article.created_at }}</p>
<p class='text-secondary'> 작성자 : {{ article.user }}</p>
<hr>
<p>{{ article.content }}</p>

{% comment %} {% if user.is_authenticated %} {% endcomment %}
{% if article.user == request.user %}

  <a href="{% url 'articles:update' article.pk %}">[수정하기]</a>
  <form action="{% url 'articles:delete' article.pk %}" method = 'POST'>
    {% csrf_token %}
    <button type="submit">삭제하기</button>  
  </form>

{% endif %}

  {% if user.is_authenticated %}
  <form action="{% url 'articles:comments_create' article.pk %}" method='POST'>
    {% csrf_token %}
    {{ form.as_table }}   <button type="submit">댓글작성</button>
  </form>
  {% endif %}
<hr>
  <ul>
{% for comment in comments %}
  <li>
  {% if comment.user == request.user  %}
    <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST"> 
      {% csrf_token %}
      
    <span>작성자 : {{ comment.user }} . 작성일 : {{ comment.created_at }}   </span><br>
    <span>내용 : {{ comment }}</span>
      <button type="submit" class='btn btn-danger'>댓글삭제</button>
    </form>
  {% else %}
    <span>작성자 : {{ comment.user }} . 작성일 : {{ comment.created_at }}   </span><br>
    <span>내용 : {{ comment }}</span>

  {% endif %}
  </li>
  <br>
  
{% endfor %}
  </ul>
  {% include 'articles/_follow.html' %}


{% endblock container %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block title %} Article::Index
{% endblock title %}

{% block container %}

  {% if user.is_authenticated %}
    <h2>Article List</h2>
    <a href="{% url 'articles:create' %}">[생성하기]</a>
    <hr>
  {% else %}
    <h4>로그인 해야 게시글을 만들 수 있습니다.</h4>
  {% endif %}
  {% for article in articles %}
    <div>
      <p>작성자 : {{ article.user }}</p>
      <h3>{{ article.pk }}. {{ article.title }}</h3><a href="{% url 'articles:detail' article.pk%}">[자세히보기]</a>

    </div>
    <br>
  {% endfor %}

{% endblock container %} 

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block title %} Article::Update
{% endblock title %}

{% block container %}

{% comment %}  form이 필요함 왜? 입력할 창이 필요하니까 {% endcomment %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <button type="submit">수정완료</button>
</form>
{% endblock container %}