accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'  # 이름 지정하기
urlpatterns = [
    path('create/', views.create, name='create' ),
    path('', views.index, name='index'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/like/', views.like, name='like'),
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    # user_pk == 게시글 작성자의 유저 아이디
    path('<int:article_pk>/follow/<int:user_pk>/', views.follow, name='follow'),
    
]

review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('articles/', include('articles.urls')),  
    path('accounts/', include('accounts.urls')),  # include의 의미가 accounts 앱에 있는 urls.py의 urlpatterns를 찾으라는 뜻이므로 accounts urls.py에 해당 변수가 있어야 한다.
    path('admin/', admin.site.urls),
]

review/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="  {% static 'bootstrap/css/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="  {% static 'bootstrap/css/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="  {% static 'bootstrap/css/bootstrap.min.css' %}">
  <script src="https://kit.fontawesome.com/04eb247adc.js" crossorigin="anonymous"></script>

  <title>{% block title %}{% endblock title %}</title>
</head>
<body>
  <div class="container">
  <header>
    <h1>저희 페이지에 오신걸 환영합니다.</h1>
    {% if  user.is_authenticated  %}
      <p>
        <span>Hello, {{ user.username }}</span>
        <a href="{% url 'accounts:logout' %}">[로그아웃]</a>
        <a href="{% url 'accounts:update' %}">[회원정보수정]</a>
        <form action="{% url 'accounts:delete' %}" method="POST">
          {% csrf_token %}
          <button type="submit">회원탈퇴</button>
        </form>

      </p>
    {% else %}
        <a href="{% url 'accounts:login' %}">[로그인]</a>
        <a href="{% url 'accounts:signup' %}">[회원가입]</a>
    
    {% endif %}
  </header>
  <a href="{% url 'articles:index' %}">[목록]</a>
<hr>
    {% block container %}{% endblock container %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="  {% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>